const amenityConfig = {
    "carry-on": { icon: "🧳", label: "Carry-on" },
    "flexible-rebooking": { icon: "🔁", label: "Flexible" },
    "checked-bag": { icon: "🎒", label: "Checked bag" },
    meals: { icon: "🍱", label: "Meals" },
    wifi: { icon: "📶", label: "Wi-Fi" },
    breakfast: { icon: "🥐", label: "Breakfast" },
    parking: { icon: "🅿️", label: "Parking" },
    "automatic": { icon: "⚙️", label: "Automatic" },
    "insurance": { icon: "🛡️", label: "Insurance" },
    "unlimited-mileage": { icon: "🧭", label: "Unlimited" },
    "chef-selection": { icon: "👨‍🍳", label: "Chef" },
    indoor: { icon: "🏠", label: "Indoor" },
    outdoor: { icon: "🌿", label: "Outdoor" },
    "private-room": { icon: "🔒", label: "Private" },
    "custom-menu": { icon: "🧾", label: "Custom menu" },
    "dedicated-host": { icon: "🤝", label: "Host" },
    buffet: { icon: "🍽️", label: "Buffet" },
    setup: { icon: "🧰", label: "Setup" },
    staff: { icon: "🙋", label: "Staff" },
    "vip-entry": { icon: "💎", label: "VIP" },
    "merch-bundle": { icon: "🛍️", label: "Merch" },
    "great-view": { icon: "👀", label: "Great view" },
    recliner: { icon: "🛋️", label: "Recliner" },
    snacks: { icon: "🍿", label: "Snacks" },
    "dolby-sound": { icon: "🔊", label: "Dolby" },
    courtside: { icon: "🏀", label: "Courtside" },
    "fan-zone": { icon: "📣", label: "Fan zone" },
    consultation: { icon: "🩺", label: "Consult" },
    "follow-up": { icon: "📅", label: "Follow-up" },
    "priority-slot": { icon: "⚡", label: "Priority" },
    wash: { icon: "🚿", label: "Wash" },
    styling: { icon: "✨", label: "Styling" },
    "beard-trim": { icon: "🧔", label: "Beard trim" },
    "aromatherapy": { icon: "🌸", label: "Aroma" },
    "hot-stone": { icon: "🪨", label: "Hot stone" },
    equipment: { icon: "🏸", label: "Equipment" },
    lighting: { icon: "💡", label: "Lighting" },
    showers: { icon: "🚿", label: "Showers" },
    projector: { icon: "📽️", label: "Projector" },
    refreshments: { icon: "☕", label: "Refreshments" },
    backdrops: { icon: "🖼️", label: "Backdrops" },
    assistant: { icon: "🙋", label: "Assistant" },
    availability: { icon: "📦", label: "Available" },
    support: { icon: "🧑‍💻", label: "Support" },
    secure: { icon: "🔐", label: "Secure" },
};

const accentClasses = {
    cyan: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-cyan-400",
        accent: "text-ledger-text",
    },
    violet: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-violet-400",
        accent: "text-ledger-text",
    },
    amber: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-amber-400",
        accent: "text-ledger-text",
    },
    pink: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-pink-400",
        accent: "text-ledger-text",
    },
    purple: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-purple-400",
        accent: "text-ledger-text",
    },
    green: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-emerald-400",
        accent: "text-ledger-text",
    },
    blue: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-blue-400",
        accent: "text-ledger-text",
    },
    slate: {
        border: "border-ledger-border",
        badge: "bf-market-badge",
        glow: "",
        button: "text-ledger-text hover:underline",
        ring: "focus:border-cyan-400",
        accent: "text-ledger-text",
    },
};

const getAccentClasses = (color) =>
    accentClasses[color] ?? accentClasses.slate;

export { amenityConfig, getAccentClasses };
