const amenityConfig = {
    "carry-on": { icon: "🧳", label: "Carry-on" },
    "flexible-rebooking": { icon: "🔁", label: "Flexible" },
    "checked-bag": { icon: "🎒", label: "Checked bag" },
    meals: { icon: "🍱", label: "Meals" },
    wifi: { icon: "📶", label: "Wi-Fi" },
    breakfast: { icon: "🥐", label: "Breakfast" },
    parking: { icon: "🅿️", label: "Parking" },
    "automatic": { icon: "⚙️", label: "Automatic" },
    "insurance": { icon: "🛡️", label: "Insurance" },
    "unlimited-mileage": { icon: "🧭", label: "Unlimited" },
    "chef-selection": { icon: "👨‍🍳", label: "Chef" },
    indoor: { icon: "🏠", label: "Indoor" },
    outdoor: { icon: "🌿", label: "Outdoor" },
    "private-room": { icon: "🔒", label: "Private" },
    "custom-menu": { icon: "🧾", label: "Custom menu" },
    "dedicated-host": { icon: "🤝", label: "Host" },
    buffet: { icon: "🍽️", label: "Buffet" },
    setup: { icon: "🧰", label: "Setup" },
    staff: { icon: "🙋", label: "Staff" },
    "vip-entry": { icon: "💎", label: "VIP" },
    "merch-bundle": { icon: "🛍️", label: "Merch" },
    "great-view": { icon: "👀", label: "Great view" },
    recliner: { icon: "🛋️", label: "Recliner" },
    snacks: { icon: "🍿", label: "Snacks" },
    "dolby-sound": { icon: "🔊", label: "Dolby" },
    courtside: { icon: "🏀", label: "Courtside" },
    "fan-zone": { icon: "📣", label: "Fan zone" },
    consultation: { icon: "🩺", label: "Consult" },
    "follow-up": { icon: "📅", label: "Follow-up" },
    "priority-slot": { icon: "⚡", label: "Priority" },
    wash: { icon: "🚿", label: "Wash" },
    styling: { icon: "✨", label: "Styling" },
    "beard-trim": { icon: "🧔", label: "Beard trim" },
    "aromatherapy": { icon: "🌸", label: "Aroma" },
    "hot-stone": { icon: "🪨", label: "Hot stone" },
    equipment: { icon: "🏸", label: "Equipment" },
    lighting: { icon: "💡", label: "Lighting" },
    showers: { icon: "🚿", label: "Showers" },
    projector: { icon: "📽️", label: "Projector" },
    refreshments: { icon: "☕", label: "Refreshments" },
    backdrops: { icon: "🖼️", label: "Backdrops" },
    assistant: { icon: "🙋", label: "Assistant" },
    availability: { icon: "📦", label: "Available" },
    support: { icon: "🧑‍💻", label: "Support" },
    secure: { icon: "🔐", label: "Secure" },
};

const accentClasses = {
    cyan: {
        border: "border-cyan-400/70",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-cyan-400/70 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(34,211,238,0.6)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-cyan-400",
        accent: "text-cyan-300",
    },
    violet: {
        border: "border-violet-400/70",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-violet-400/70 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(167,139,250,0.6)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-violet-400",
        accent: "text-violet-200",
    },
    amber: {
        border: "border-amber-400/70",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-amber-400/70 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(251,191,36,0.6)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-amber-400",
        accent: "text-amber-200",
    },
    pink: {
        border: "border-pink-400/70",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-pink-400/70 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(244,114,182,0.6)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-pink-400",
        accent: "text-pink-200",
    },
    purple: {
        border: "border-purple-400/70",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-purple-400/70 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(192,132,252,0.6)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-purple-400",
        accent: "text-purple-200",
    },
    green: {
        border: "border-emerald-400/70",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-emerald-400/70 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(52,211,153,0.6)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-emerald-400",
        accent: "text-emerald-200",
    },
    blue: {
        border: "border-blue-400/70",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-blue-400/70 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(96,165,250,0.6)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-blue-400",
        accent: "text-blue-200",
    },
    slate: {
        border: "border-white/10",
        badge: "bg-slate-950/95 text-slate-100 ring-1 ring-white/30 backdrop-blur border-transparent",
        glow: "hover:shadow-[0_20px_60px_-25px_rgba(148,163,184,0.4)]",
        button: "bg-cyan-500 hover:bg-cyan-400 text-slate-950",
        ring: "focus:border-cyan-400",
        accent: "text-slate-200",
    },
};

const getAccentClasses = (color) =>
    accentClasses[color] ?? accentClasses.slate;

export { amenityConfig, getAccentClasses };
